//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVE_ORDERS
    {
        public int MOVE_ORDER_ID { get; set; }
        public string MOVE_ORDER_NUMBER { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<int> STORE_ID { get; set; }
        public Nullable<int> STOCK_ID { get; set; }
    
        public virtual ITEMS ITEMS { get; set; }
        public virtual STOCKS STOCKS { get; set; }
        public virtual STORE STORE { get; set; }
    }
}
