//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleCo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUYERS> BUYERS { get; set; }
        public virtual DbSet<DISTRICT> DISTRICT { get; set; }
        public virtual DbSet<ITEMS> ITEMS { get; set; }
        public virtual DbSet<ITEMS_CATEGORY> ITEMS_CATEGORY { get; set; }
        public virtual DbSet<ITEMS_PURCHASE> ITEMS_PURCHASE { get; set; }
        public virtual DbSet<MOVE_ORDERS> MOVE_ORDERS { get; set; }
        public virtual DbSet<SALES> SALES { get; set; }
        public virtual DbSet<SALES_STORE> SALES_STORE { get; set; }
        public virtual DbSet<STOCKS> STOCKS { get; set; }
        public virtual DbSet<STORE> STORE { get; set; }
        public virtual DbSet<SUPPLIERS> SUPPLIERS { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSE { get; set; }
    }
}
