//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_STORE
    {
        public int ORDER_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<System.DateTime> PURCHASE_DATE { get; set; }
        public Nullable<int> STORE_ID { get; set; }
        public Nullable<int> BUYER_ID { get; set; }
    
        public virtual BUYERS BUYERS { get; set; }
        public virtual ITEMS ITEMS { get; set; }
        public virtual STORE STORE { get; set; }
    }
}
