//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES
    {
        public int ORDER_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> OREDER_QUANTITY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    }
}
