//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleCo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        public int ITEM_ID { get; set; }
        public string ITEM_DESCRIPTION { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<int> SOK { get; set; }
    }
}
